# --------------------
# Core spring settings
# --------------------

spring:

  application:
    version: '1.0.0'

  server:
    port: 8080

# --------------------------------
# Admin/actuator endpoint settings
# --------------------------------

management.endpoints.web:
  base-path: /admin
  exposure.include: '*'
  exposure.exclude: shutdown


# -----------------------------------------------
# Build information, /admin/info and /admin/build
# -----------------------------------------------

info.app.name: ${spring.application.name}
info.app.profile: ${spring.profiles.active}
info.app.maven.version: '1.0.0'
info.app.maven.artifactId: 'springai'
info.app.maven.groupId: 'com.leonardo'
info.app.ci.build: 'unknown'
info.app.ci.url: 'ci-url'

# ---------------
# Zipkin settings
# ---------------

#spring.zipkin.baseUrl: localhost:9411
#spring.sleuth.keys.http.headers

# ----------------
# Logging settings
# ----------------

logging.level.: ERROR
logging.level.com.shedhack: ERROR

# ---------------
# Server settings
# ---------------

server:
  port: 8080

---
# ----------------------------------
# Local/development profile settings
# ----------------------------------

spring:
  profiles: local

  security:
    user.name: local
    user.password: local

---
# -----------------------------------------------
# Test/Staging/CI build deployed profile settings
# -----------------------------------------------

spring:
  profiles: test


---
# ---------------------------
# Production profile settings
# ---------------------------

spring:
  profiles: production






